# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_completed', models.BooleanField(db_index=True)),
                ('notes', models.TextField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
